import React,{useCallback,useMemo,useState}from'react';
import{ActivityIndicator,FlatList,RefreshControl,StatusBar,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';

import { SafeAreaView } from 'react-native-safe-area-context';
import{useFocusEffect}from'@react-navigation/native';
import{useTheme}from'../../context/ThemeContext';
import{getAdminReports}from'../../services/adminService';
const Icon=({name,size=20,color})=><Ionicons name={name} size={size} color={color}/>;const FILTERS=[['all','Todos'],['open','Abiertos'],['in_review','En revisión'],['resolved','Resueltos'],['closed','Cerrados']];const listOf=r=>Array.isArray(r)?r:r?.items||r?.reports||r?.results||[];const date=v=>{if(!v)return'-';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleDateString('es-AR')};
function conf(st,C){return{open:['Abierto',C.red,'mail-unread-outline'],in_review:['En revisión',C.orange,'eye-outline'],resolved:['Resuelto',C.accent,'checkmark-circle-outline'],closed:['Cerrado',C.textSecondary,'archive-outline']}[st]||[st||'Sin estado',C.textSecondary,'help-circle-outline']}
function Card({r,onPress,s,C}){const[c,color,icon]=conf(r?.status,C);return <TouchableOpacity style={s.card} onPress={onPress}><View style={[s.icon,{backgroundColor:`${color}16`}]}><Icon name={icon} color={color}/></View><View style={s.body}><View style={s.top}><Text style={s.subject} numberOfLines={1}>{r?.subject||'Reporte sin asunto'}</Text><Text style={s.id}>#{r?.id??'-'}</Text></View><Text style={s.meta} numberOfLines={1}>{r?.user?.email||r?.user_email||r?.email||'Usuario no disponible'}</Text><View style={s.bottom}><Text style={[s.badge,{color,backgroundColor:`${color}14`}]}>{c}</Text><Text style={s.date}>{date(r?.created_at)}</Text></View></View><Icon name="chevron-forward" color={C.textMuted}/></TouchableOpacity>}
export default function AdminReportsScreen({navigation}){const{colors:C,isDark}=useTheme(),s=useMemo(()=>styles(C),[C]);const[reports,setReports]=useState([]),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');const load=useCallback(async(silent=false)=>{try{if(!silent)setLoading(true);setError('');setReports(listOf(await getAdminReports({status:filter,search:search.trim()||undefined})));}catch(e){setError(e?.message||'No se pudieron cargar los reportes.')}finally{setLoading(false);setRefreshing(false)}},[filter,search]);useFocusEffect(useCallback(()=>{load()},[load]));
return <SafeAreaView edges={['top']} style={s.flex}><StatusBar barStyle={isDark?'light-content':'dark-content'} backgroundColor={C.bg}/><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>navigation.goBack()}><Icon name="arrow-back" color={C.textPrimary}/></TouchableOpacity><View style={{marginLeft:13}}><Text style={s.title}>Reportes de soporte</Text><Text style={s.subtitle}>Seguimiento y respuestas</Text></View></View>{loading?<View style={s.center}><ActivityIndicator size="large" color={C.accent}/><Text style={s.loading}>Cargando reportes...</Text></View>:<FlatList data={reports} keyExtractor={(x,i)=>String(x?.id??i)} renderItem={({item})=><Card r={item} onPress={()=>navigation.navigate('AdminReportDetail',{reportId:item.id,report:item})} s={s} C={C}/>} ListHeaderComponent={<><View style={s.search}><Icon name="search-outline" color={C.textSecondary}/><TextInput value={search} onChangeText={setSearch} onSubmitEditing={()=>load()} placeholder="Buscar por asunto, correo o ID" placeholderTextColor={C.textMuted} style={s.input}/></View><FlatList horizontal data={FILTERS} keyExtractor={x=>x[0]} showsHorizontalScrollIndicator={false} contentContainerStyle={{paddingVertical:13}} renderItem={({item})=><TouchableOpacity style={[s.chip,filter===item[0]&&s.chipOn]} onPress={()=>setFilter(item[0])}><Text style={[s.chipText,filter===item[0]&&{color:C.accent}]}>{item[1]}</Text></TouchableOpacity>}/>{!!error&&<View style={s.error}><Text style={s.errorText}>{error}</Text></View>}<Text style={s.count}>{reports.length} reportes cargados</Text></>} ListEmptyComponent={<View style={s.empty}><Icon name="document-text-outline" size={36} color={C.textMuted}/><Text style={s.emptyTitle}>No hay reportes</Text><Text style={s.emptyText}>No se encontraron resultados.</Text></View>} ListFooterComponent={<Text style={s.footer}>Spendly © 2026</Text>} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true)}} tintColor={C.accent} colors={[C.accent]}/>}/>}</SafeAreaView>}
function styles(C){return StyleSheet.create({flex:{flex:1,backgroundColor:C.bg},header:{flexDirection:'row',alignItems:'center',padding:18,borderBottomWidth:1,borderBottomColor:C.border},back:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border},title:{color:C.textPrimary,fontSize:20,fontWeight:'800'},subtitle:{color:C.textSecondary,fontSize:12,marginTop:2},center:{flex:1,alignItems:'center',justifyContent:'center'},loading:{color:C.textSecondary,marginTop:12},content:{padding:18,flexGrow:1},search:{height:50,flexDirection:'row',alignItems:'center',paddingHorizontal:14,backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:16},input:{flex:1,color:C.textPrimary,marginLeft:9},chip:{paddingHorizontal:15,paddingVertical:9,borderRadius:99,backgroundColor:C.surface,borderWidth:1,borderColor:C.border,marginRight:8},chipOn:{backgroundColor:`${C.accent}18`,borderColor:`${C.accent}55`},chipText:{color:C.textSecondary,fontSize:12,fontWeight:'700'},count:{color:C.textMuted,fontSize:11,marginBottom:10},card:{flexDirection:'row',alignItems:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:18,padding:14,marginBottom:10},icon:{width:46,height:46,borderRadius:15,alignItems:'center',justifyContent:'center',marginRight:12},body:{flex:1},top:{flexDirection:'row'},subject:{flex:1,color:C.textPrimary,fontSize:14,fontWeight:'800'},id:{color:C.textMuted,fontSize:10},meta:{color:C.textSecondary,fontSize:11,marginTop:4},bottom:{flexDirection:'row',alignItems:'center',marginTop:8},badge:{fontSize:10,fontWeight:'800',paddingHorizontal:8,paddingVertical:4,borderRadius:99},date:{color:C.textMuted,fontSize:10,marginLeft:8},error:{backgroundColor:`${C.red}10`,borderWidth:1,borderColor:`${C.red}35`,borderRadius:14,padding:12,marginBottom:12},errorText:{color:C.textSecondary,fontSize:12},empty:{alignItems:'center',paddingVertical:55},emptyTitle:{color:C.textPrimary,fontSize:16,fontWeight:'800',marginTop:12},emptyText:{color:C.textSecondary,fontSize:13,marginTop:5},footer:{color:C.textMuted,fontSize:12,textAlign:'center',marginTop:22}})}
