import React,{useCallback,useMemo,useState}from'react';
import{ActivityIndicator,Alert,RefreshControl,ScrollView,StatusBar,StyleSheet,Text,TouchableOpacity,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';

import { SafeAreaView } from 'react-native-safe-area-context';
import{useFocusEffect}from'@react-navigation/native';
import{useTheme}from'../../context/ThemeContext';
import{getAdminUser,updateAdminUserRole,updateAdminUserStatus}from'../../services/adminService';
const Icon=({name,size=20,color})=><Ionicons name={name} size={size} color={color}/>;const initials=n=>(n||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();const date=v=>{if(!v)return'Sin información';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('es-AR')};
function Info({label,value,icon,color,s}){return <View style={s.info}><View style={[s.infoIcon,{backgroundColor:`${color}16`}]}><Icon name={icon} color={color}/></View><View><Text style={s.infoLabel}>{label}</Text><Text style={s.infoValue}>{value||'Sin información'}</Text></View></View>}
export default function AdminUserDetailScreen({navigation,route}){const{colors:C,isDark}=useTheme(),s=useMemo(()=>styles(C),[C]),id=route?.params?.userId??route?.params?.user?.id;const[user,setUser]=useState(route?.params?.user||null),[loading,setLoading]=useState(!user),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
const load=useCallback(async(silent=false)=>{try{if(!silent)setLoading(true);setError('');const r=await getAdminUser(id);setUser(r?.user||r)}catch(e){setError(e?.message||'No se pudo cargar el usuario.')}finally{setLoading(false);setRefreshing(false)}},[id]);useFocusEffect(useCallback(()=>{load(!!user)},[load]));
const status=()=>Alert.alert(user?.is_active!==false?'Desactivar usuario':'Activar usuario','¿Confirmás esta acción?',[{text:'Cancelar',style:'cancel'},{text:'Confirmar',style:user?.is_active!==false?'destructive':'default',onPress:async()=>{try{setBusy(true);const active=user?.is_active===false;const r=await updateAdminUserStatus(id,active);setUser(x=>({...x,...(r?.user||r),is_active:active}))}catch(e){Alert.alert('Error',e?.message||'No se pudo actualizar.')}finally{setBusy(false)}}}]);
const role=()=>Alert.alert(user?.role==='admin'?'Quitar rol administrador':'Asignar rol administrador','¿Confirmás el cambio de permisos?',[{text:'Cancelar',style:'cancel'},{text:'Confirmar',onPress:async()=>{try{setBusy(true);const next=user?.role==='admin'?'user':'admin';const r=await updateAdminUserRole(id,next);setUser(x=>({...x,...(r?.user||r),role:next}))}catch(e){Alert.alert('Error',e?.message||'No se pudo actualizar.')}finally{setBusy(false)}}}]);
if(loading)return <View style={s.center}><StatusBar barStyle={isDark?'light-content':'dark-content'} backgroundColor={C.bg}/><ActivityIndicator size="large" color={C.accent}/></View>;
return <SafeAreaView edges={['top']} style={s.flex}><StatusBar barStyle={isDark?'light-content':'dark-content'} backgroundColor={C.bg}/><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>navigation.goBack()}><Icon name="arrow-back" color={C.textPrimary}/></TouchableOpacity><View style={{marginLeft:13}}><Text style={s.title}>Detalle del usuario</Text><Text style={s.subtitle}>ID #{id??'-'}</Text></View></View><ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true)}} tintColor={C.accent} colors={[C.accent]}/>}>
{!!error&&<View style={s.error}><Text style={s.errorText}>{error}</Text></View>}{user&&<><View style={s.profile}><View style={s.avatar}><Text style={s.avatarText}>{initials(user.full_name)}</Text></View><Text style={s.name}>{user.full_name||'Usuario sin nombre'}</Text><Text style={s.email}>{user.email||'Sin correo'}</Text><View style={s.badges}><Text style={[s.badge,{color:user.is_active!==false?C.accent:C.red}]}>{user.is_active!==false?'Cuenta activa':'Cuenta inactiva'}</Text><Text style={[s.badge,{color:user.role==='admin'?C.purple:C.blue}]}>{user.role==='admin'?'Administrador':'Usuario'}</Text></View></View><Text style={s.section}>Información</Text><View style={s.card}><Info label="Correo" value={user.email} icon="mail-outline" color={C.blue} s={s}/><Info label="Moneda" value={user.preferred_currency} icon="cash-outline" color={C.accent} s={s}/><Info label="Registro" value={date(user.created_at)} icon="calendar-outline" color={C.orange} s={s}/><Info label="Último heartbeat" value={date(user.last_heartbeat_at)} icon="radio-outline" color={C.purple} s={s}/></View><Text style={s.section}>Acciones administrativas</Text><TouchableOpacity style={s.action} onPress={status} disabled={busy}><Icon name={user.is_active!==false?'person-remove-outline':'person-add-outline'} color={user.is_active!==false?C.red:C.accent}/><Text style={s.actionText}>{user.is_active!==false?'Desactivar cuenta':'Activar cuenta'}</Text></TouchableOpacity><TouchableOpacity style={s.action} onPress={role} disabled={busy}><Icon name="shield-checkmark-outline" color={C.purple}/><Text style={s.actionText}>{user.role==='admin'?'Quitar rol administrador':'Convertir en administrador'}</Text></TouchableOpacity>{busy&&<ActivityIndicator style={{marginTop:15}} color={C.accent}/>}</>}<Text style={s.footer}>Spendly © 2026</Text></ScrollView></SafeAreaView>}
function styles(C){return StyleSheet.create({flex:{flex:1,backgroundColor:C.bg},center:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:C.bg},header:{flexDirection:'row',alignItems:'center',padding:18,borderBottomWidth:1,borderBottomColor:C.border},back:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border},title:{color:C.textPrimary,fontSize:20,fontWeight:'800'},subtitle:{color:C.textSecondary,fontSize:12,marginTop:2},content:{padding:18,paddingBottom:36},profile:{alignItems:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:22,padding:22},avatar:{width:76,height:76,borderRadius:25,alignItems:'center',justifyContent:'center',backgroundColor:`${C.accent}16`},avatarText:{color:C.accent,fontSize:25,fontWeight:'900'},name:{color:C.textPrimary,fontSize:20,fontWeight:'900',marginTop:14},email:{color:C.textSecondary,fontSize:13,marginTop:4},badges:{flexDirection:'row',marginTop:13},badge:{backgroundColor:C.bg,paddingHorizontal:10,paddingVertical:6,borderRadius:99,marginHorizontal:4,fontSize:10,fontWeight:'800'},section:{color:C.textSecondary,fontSize:12,fontWeight:'800',textTransform:'uppercase',letterSpacing:.8,marginTop:22,marginBottom:10},card:{backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:18,overflow:'hidden'},info:{flexDirection:'row',alignItems:'center',padding:14,borderBottomWidth:1,borderBottomColor:C.border},infoIcon:{width:40,height:40,borderRadius:13,alignItems:'center',justifyContent:'center',marginRight:12},infoLabel:{color:C.textMuted,fontSize:10,fontWeight:'700',textTransform:'uppercase'},infoValue:{color:C.textPrimary,fontSize:13,fontWeight:'600',marginTop:3},action:{flexDirection:'row',alignItems:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:17,padding:15,marginBottom:10},actionText:{color:C.textPrimary,fontSize:14,fontWeight:'800',marginLeft:11},error:{backgroundColor:`${C.red}10`,borderWidth:1,borderColor:`${C.red}35`,borderRadius:14,padding:12,marginBottom:12},errorText:{color:C.textSecondary},footer:{color:C.textMuted,fontSize:12,textAlign:'center',marginTop:30}})}
