import React,{useCallback,useMemo,useState}from'react';
import{ActivityIndicator,FlatList,RefreshControl,StatusBar,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';

import { SafeAreaView } from 'react-native-safe-area-context';
import{useFocusEffect}from'@react-navigation/native';
import{useTheme}from'../../context/ThemeContext';
import{getAdminUsers}from'../../services/adminService';
const Icon=({name,size=20,color})=><Ionicons name={name} size={size} color={color}/>;
const FILTERS=[['all','Todos'],['active','Activos'],['inactive','Inactivos'],['admin','Admins'],['online','En línea']];
const listOf=r=>Array.isArray(r)?r:r?.items||r?.users||r?.results||[];
const initials=n=>(n||'U').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function Card({u,onPress,s,C}){const admin=u?.role==='admin',active=u?.is_active!==false,online=!!(u?.is_online??u?.online);return <TouchableOpacity style={s.card} onPress={onPress}><View style={s.avatar}><Text style={s.avatarText}>{initials(u?.full_name)}</Text>{online&&<View style={s.online}/>}</View><View style={s.body}><View style={s.nameRow}><Text style={s.name} numberOfLines={1}>{u?.full_name||'Usuario sin nombre'}</Text>{admin&&<View style={s.admin}><Text style={s.adminText}>Admin</Text></View>}</View><Text style={s.email} numberOfLines={1}>{u?.email||'Sin correo'}</Text><View style={[s.badge,{backgroundColor:active?`${C.accent}16`:`${C.red}14`}]}><Text style={{color:active?C.accent:C.red,fontSize:10,fontWeight:'800'}}>{active?'Activo':'Inactivo'}</Text></View></View><Icon name="chevron-forward" color={C.textMuted}/></TouchableOpacity>}
export default function AdminUsersScreen({navigation}){const{colors:C,isDark}=useTheme();const s=useMemo(()=>styles(C),[C]);const[users,setUsers]=useState([]),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
const load=useCallback(async(silent=false)=>{try{if(!silent)setLoading(true);setError('');setUsers(listOf(await getAdminUsers({search:search.trim()||undefined,status:filter})));}catch(e){setError(e?.message||'No se pudieron cargar los usuarios.')}finally{setLoading(false);setRefreshing(false)}},[search,filter]);
useFocusEffect(useCallback(()=>{load()},[load]));
return <SafeAreaView edges={['top']} style={s.flex}><StatusBar barStyle={isDark?'light-content':'dark-content'} backgroundColor={C.bg}/><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>navigation.goBack()}><Icon name="arrow-back" color={C.textPrimary}/></TouchableOpacity><View style={{marginLeft:13}}><Text style={s.title}>Usuarios</Text><Text style={s.subtitle}>Cuentas y permisos</Text></View></View>{loading?<View style={s.center}><ActivityIndicator size="large" color={C.accent}/><Text style={s.loading}>Cargando usuarios...</Text></View>:<FlatList data={users} keyExtractor={(x,i)=>String(x?.id??i)} renderItem={({item})=><Card u={item} onPress={()=>navigation.navigate('AdminUserDetail',{userId:item.id,user:item})} s={s} C={C}/>} ListHeaderComponent={<><View style={s.search}><Icon name="search-outline" color={C.textSecondary}/><TextInput value={search} onChangeText={setSearch} onSubmitEditing={()=>load()} placeholder="Buscar por nombre o correo" placeholderTextColor={C.textMuted} style={s.input}/></View><FlatList horizontal data={FILTERS} keyExtractor={x=>x[0]} showsHorizontalScrollIndicator={false} contentContainerStyle={{paddingVertical:13}} renderItem={({item})=><TouchableOpacity style={[s.chip,filter===item[0]&&s.chipOn]} onPress={()=>setFilter(item[0])}><Text style={[s.chipText,filter===item[0]&&{color:C.accent}]}>{item[1]}</Text></TouchableOpacity>}/>{!!error&&<View style={s.error}><Icon name="alert-circle-outline" color={C.red}/><Text style={s.errorText}>{error}</Text></View>}<Text style={s.count}>{users.length} usuarios cargados</Text></>} ListEmptyComponent={<View style={s.empty}><Icon name="people-outline" size={36} color={C.textMuted}/><Text style={s.emptyTitle}>No se encontraron usuarios</Text><Text style={s.emptyText}>Probá con otra búsqueda o filtro.</Text></View>} ListFooterComponent={<Text style={s.footer}>Spendly © 2026</Text>} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true)}} tintColor={C.accent} colors={[C.accent]}/>}/>}</SafeAreaView>}
function styles(C){return StyleSheet.create({flex:{flex:1,backgroundColor:C.bg},header:{flexDirection:'row',alignItems:'center',padding:18,borderBottomWidth:1,borderBottomColor:C.border},back:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border},title:{color:C.textPrimary,fontSize:20,fontWeight:'800'},subtitle:{color:C.textSecondary,fontSize:12,marginTop:2},center:{flex:1,alignItems:'center',justifyContent:'center'},loading:{color:C.textSecondary,marginTop:12},content:{padding:18,flexGrow:1},search:{height:50,flexDirection:'row',alignItems:'center',paddingHorizontal:14,backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:16},input:{flex:1,color:C.textPrimary,marginLeft:9},chip:{paddingHorizontal:15,paddingVertical:9,borderRadius:99,backgroundColor:C.surface,borderWidth:1,borderColor:C.border,marginRight:8},chipOn:{backgroundColor:`${C.accent}18`,borderColor:`${C.accent}55`},chipText:{color:C.textSecondary,fontSize:12,fontWeight:'700'},count:{color:C.textMuted,fontSize:11,marginBottom:10},card:{flexDirection:'row',alignItems:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:18,padding:14,marginBottom:10},avatar:{width:49,height:49,borderRadius:16,alignItems:'center',justifyContent:'center',backgroundColor:`${C.accent}16`,marginRight:12},avatarText:{color:C.accent,fontWeight:'900'},online:{position:'absolute',right:-2,bottom:-2,width:13,height:13,borderRadius:7,backgroundColor:C.accent,borderWidth:2,borderColor:C.surface},body:{flex:1},nameRow:{flexDirection:'row',alignItems:'center'},name:{flexShrink:1,color:C.textPrimary,fontSize:14,fontWeight:'800'},email:{color:C.textSecondary,fontSize:12,marginTop:3},admin:{backgroundColor:`${C.purple}16`,borderRadius:99,paddingHorizontal:7,paddingVertical:3,marginLeft:7},adminText:{color:C.purple,fontSize:9,fontWeight:'800'},badge:{alignSelf:'flex-start',paddingHorizontal:8,paddingVertical:4,borderRadius:99,marginTop:8},error:{flexDirection:'row',alignItems:'center',backgroundColor:`${C.red}10`,borderWidth:1,borderColor:`${C.red}35`,borderRadius:14,padding:12,marginBottom:12},errorText:{color:C.textSecondary,fontSize:12,marginLeft:9},empty:{alignItems:'center',paddingVertical:55},emptyTitle:{color:C.textPrimary,fontSize:16,fontWeight:'800',marginTop:12},emptyText:{color:C.textSecondary,fontSize:13,marginTop:5},footer:{color:C.textMuted,fontSize:12,textAlign:'center',marginTop:22}})}
