import React,{useCallback,useMemo,useState}from'react';
import{ActivityIndicator,Alert,RefreshControl,ScrollView,StatusBar,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';

import { SafeAreaView } from 'react-native-safe-area-context';
import{useFocusEffect}from'@react-navigation/native';
import{useTheme}from'../../context/ThemeContext';
import{getAdminScannerHealth,getAdminToolsHealth,sendAdminTestEmail,sendAdminTestNotification}from'../../services/adminService';
const Icon=({name,size=20,color})=><Ionicons name={name} size={size} color={color}/>;
function Service({title,desc,status,icon,s,C}){
  const config={
    healthy:{label:'Operativo',color:C.accent},
    warning:{label:'Advertencia',color:C.orange},
    error:{label:'No disponible',color:C.red},
    unknown:{label:'Sin comprobar',color:C.textSecondary},
  }[status]||{label:'Sin comprobar',color:C.textSecondary};
  return <View style={s.service}><View style={[s.serviceIcon,{backgroundColor:`${config.color}16`}]}><Icon name={icon} color={config.color}/></View><View style={{flex:1}}><Text style={s.serviceTitle}>{title}</Text><Text style={s.serviceDesc}>{desc}</Text></View><Text style={[s.state,{color:config.color,backgroundColor:`${config.color}15`}]}>{config.label}</Text></View>
}
export default function AdminToolsScreen({navigation}){const{colors:C,isDark}=useTheme(),s=useMemo(()=>styles(C),[C]);const[health,setHealth]=useState(null),[scanner,setScanner]=useState(null),[email,setEmail]=useState(''),[userId,setUserId]=useState(''),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState('');
const load=useCallback(async(silent=false)=>{try{if(!silent)setLoading(true);setError('');const[a,b]=await Promise.allSettled([getAdminToolsHealth(),getAdminScannerHealth()]);setHealth(a.status==='fulfilled'?a.value:{status:'error'});setScanner(b.status==='fulfilled'?b.value:{status:'error'});}catch(e){setError(e?.message||'No se pudo consultar el sistema.')}finally{setLoading(false);setRefreshing(false)}},[]);useFocusEffect(useCallback(()=>{load()},[load]));
const emailTest=async()=>{if(!email.trim())return;try{setBusy('email');const r=await sendAdminTestEmail(email.trim());Alert.alert('Prueba completada',r?.message||'Correo procesado.')}catch(e){Alert.alert('Error',e?.message||'No se pudo enviar.')}finally{setBusy('')}};
const notificationTest=async()=>{const id=Number(userId);if(!userId.trim()||isNaN(id))return Alert.alert('ID inválido','Ingresá un ID de usuario válido.');try{setBusy('notification');const r=await sendAdminTestNotification(id);Alert.alert('Prueba completada',r?.message||'Notificación procesada.')}catch(e){Alert.alert('Error',e?.message||'No se pudo enviar.')}finally{setBusy('')}};
const normalizeStatus=(value)=>{
  if(value===true||value?.healthy===true||value?.ok===true||value?.connected===true)return'healthy';
  if(value===false||value?.healthy===false||value?.ok===false||value?.connected===false)return'error';
  const raw=typeof value==='string'?value:value?.status||value?.state||value?.health||value?.result;
  if(raw==null||raw==='')return'unknown';
  const v=String(raw).toLowerCase();
  if(['ok','healthy','success','operational','online','connected','available','ready','running'].includes(v))return'healthy';
  if(['error','failed','failure','unhealthy','offline','disconnected','unavailable','down'].includes(v))return'error';
  if(v.includes('warn')||v.includes('degrad'))return'warning';
  return'unknown';
};
const apiStatus=normalizeStatus(health);
const dbStatus=normalizeStatus(health?.database??health?.database_connected??health?.db??health?.db_status);
const scanStatus=normalizeStatus(scanner);
return <SafeAreaView edges={['top']} style={s.flex}><StatusBar barStyle={isDark?'light-content':'dark-content'} backgroundColor={C.bg}/><View style={s.header}><TouchableOpacity style={s.back} onPress={()=>navigation.goBack()}><Icon name="arrow-back" color={C.textPrimary}/></TouchableOpacity><View style={{marginLeft:13}}><Text style={s.title}>Herramientas</Text><Text style={s.subtitle}>Diagnóstico y pruebas internas</Text></View></View>{loading?<View style={s.center}><ActivityIndicator size="large" color={C.accent}/></View>:<ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load(true)}} tintColor={C.accent} colors={[C.accent]}/>}>
{!!error&&<View style={s.error}><Text style={s.errorText}>{error}</Text></View>}<View style={s.notice}><Icon name="lock-closed-outline" color={C.blue}/><Text style={s.noticeText}>Funciones internas disponibles únicamente para administradores.</Text></View><Text style={s.section}>Estado de servicios</Text><Service title="API" desc={health?.detail||'Backend principal'} status={apiStatus} icon="server-outline" s={s} C={C}/><Service title="Base de datos" desc="Conexión con MariaDB" status={dbStatus} icon="albums-outline" s={s} C={C}/><Service title="Escáner" desc={scanner?.detail||'Procesamiento de tickets'} status={scanStatus} icon="scan-outline" s={s} C={C}/><Text style={s.section}>Pruebas</Text><View style={s.tool}><View style={s.toolHead}><Icon name="mail-outline" color={C.orange}/><Text style={s.toolTitle}>Correo de prueba</Text></View><Text style={s.toolDesc}>Verifica la configuración SMTP y el envío.</Text><TextInput value={email} onChangeText={setEmail} placeholder="destino@correo.com" placeholderTextColor={C.textMuted} keyboardType="email-address" autoCapitalize="none" style={s.input}/><TouchableOpacity style={[s.button,(!email.trim()||busy)&&{opacity:.5}]} onPress={emailTest} disabled={!email.trim()||!!busy}>{busy==='email'?<ActivityIndicator color={C.bg}/>:<Icon name="send-outline" color={C.bg}/>}<Text style={s.buttonText}>Enviar correo de prueba</Text></TouchableOpacity></View><View style={s.tool}><View style={s.toolHead}><Icon name="notifications-outline" color={C.purple}/><Text style={s.toolTitle}>Notificación de prueba</Text></View><Text style={s.toolDesc}>Comprueba el flujo interno para un usuario.</Text><TextInput value={userId} onChangeText={setUserId} placeholder="ID del usuario" placeholderTextColor={C.textMuted} keyboardType="number-pad" style={s.input}/><TouchableOpacity style={[s.button,(!userId.trim()||busy)&&{opacity:.5}]} onPress={notificationTest} disabled={!userId.trim()||!!busy}>{busy==='notification'?<ActivityIndicator color={C.bg}/>:<Icon name="notifications-outline" color={C.bg}/>}<Text style={s.buttonText}>Enviar notificación de prueba</Text></TouchableOpacity></View><Text style={s.footer}>Spendly © 2026</Text></ScrollView>}</SafeAreaView>}
function styles(C){return StyleSheet.create({flex:{flex:1,backgroundColor:C.bg},header:{flexDirection:'row',alignItems:'center',padding:18,borderBottomWidth:1,borderBottomColor:C.border},back:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border},title:{color:C.textPrimary,fontSize:20,fontWeight:'800'},subtitle:{color:C.textSecondary,fontSize:12,marginTop:2},center:{flex:1,alignItems:'center',justifyContent:'center'},content:{padding:18,paddingBottom:36},notice:{flexDirection:'row',alignItems:'center',backgroundColor:`${C.blue}10`,borderWidth:1,borderColor:`${C.blue}30`,borderRadius:15,padding:13},noticeText:{flex:1,color:C.textSecondary,fontSize:12,lineHeight:18,marginLeft:10},section:{color:C.textSecondary,fontSize:12,fontWeight:'800',textTransform:'uppercase',letterSpacing:.8,marginTop:22,marginBottom:10},service:{flexDirection:'row',alignItems:'center',backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:17,padding:13,marginBottom:9},serviceIcon:{width:43,height:43,borderRadius:14,alignItems:'center',justifyContent:'center',marginRight:11},serviceTitle:{color:C.textPrimary,fontSize:14,fontWeight:'800'},serviceDesc:{color:C.textSecondary,fontSize:11,marginTop:3},state:{fontSize:9,fontWeight:'900',paddingHorizontal:9,paddingVertical:5,borderRadius:99},tool:{backgroundColor:C.surface,borderWidth:1,borderColor:C.border,borderRadius:19,padding:15,marginBottom:11},toolHead:{flexDirection:'row',alignItems:'center'},toolTitle:{color:C.textPrimary,fontSize:14,fontWeight:'800',marginLeft:9},toolDesc:{color:C.textSecondary,fontSize:11,lineHeight:16,marginTop:8,marginBottom:12},input:{height:48,color:C.textPrimary,backgroundColor:C.bg,borderWidth:1,borderColor:C.border,borderRadius:14,paddingHorizontal:13,marginBottom:10},button:{minHeight:48,flexDirection:'row',alignItems:'center',justifyContent:'center',backgroundColor:C.accent,borderRadius:14},buttonText:{color:C.bg,fontSize:13,fontWeight:'900',marginLeft:8},error:{backgroundColor:`${C.red}10`,borderWidth:1,borderColor:`${C.red}35`,borderRadius:14,padding:12,marginBottom:12},errorText:{color:C.textSecondary},footer:{color:C.textMuted,fontSize:12,textAlign:'center',marginTop:28}})}
