import React,{useCallback,useMemo,useState} from 'react';
import {View,Text,ScrollView,TouchableOpacity,StyleSheet,StatusBar,ActivityIndicator,RefreshControl} from 'react-native';
import {Ionicons} from '@expo/vector-icons';
import {useFocusEffect} from '@react-navigation/native';
import {useTheme} from '../context/ThemeContext';
import {useLanguage} from '../context/LanguageContext';
import {getMySupportReports} from '../services/supportService';
const FILTERS=['all','open','in_review','resolved','closed'];
const Icon=({name,size=20,color})=><Ionicons name={name} size={size} color={color}/>;
export default function MyReportsScreen({navigation}){
 const {colors:C,isDark}=useTheme(); const {language,t}=useLanguage(); const s=useMemo(()=>styles(C),[C]);
 const [reports,setReports]=useState([]),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async(refresh=false)=>{try{refresh?setRefreshing(true):setLoading(true);setReports(await getMySupportReports({status:filter==='all'?undefined:filter})||[])}catch{setReports([])}finally{setLoading(false);setRefreshing(false)}},[filter]);
 useFocusEffect(useCallback(()=>{load(false)},[load]));
 const color=x=>x==='resolved'?C.accent:x==='in_review'?C.blue:x==='closed'?C.textMuted:C.orange;
 return <View style={s.flex}><StatusBar barStyle={isDark?'light-content':'dark-content'} backgroundColor={C.bg}/><View style={s.top}><TouchableOpacity style={s.round} onPress={()=>navigation.goBack()}><Icon name="chevron-back" size={22} color={C.textPrimary}/></TouchableOpacity><Text style={s.topTitle}>{t('support.list.title')}</Text><TouchableOpacity style={s.round} onPress={()=>navigation.navigate('ReportProblem')}><Icon name="add" size={23} color={C.accent}/></TouchableOpacity></View>{loading?<View style={s.loading}><ActivityIndicator size="large" color={C.accent}/><Text style={s.loadingText}>{t('support.list.loading')}</Text></View>:<ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)} tintColor={C.accent} colors={[C.accent]}/>}><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{FILTERS.map(x=><TouchableOpacity key={x} style={[s.chip,filter===x&&s.chipOn]} onPress={()=>setFilter(x)}><Text style={[s.chipText,filter===x&&s.chipTextOn]}>{t(`support.status.${x}`)}</Text></TouchableOpacity>)}</ScrollView>{reports.length?reports.map(r=>{const c=color(r.status);return <TouchableOpacity key={r.id} style={s.card} onPress={()=>navigation.navigate('ReportDetail',{reportId:r.id})}><View style={[s.bar,{backgroundColor:c}]}/><View style={s.header}><View style={[s.icon,{backgroundColor:`${c}18`}]}><Icon name="document-text-outline" color={c}/></View><View style={{flex:1}}><Text style={s.subject} numberOfLines={2}>{r.subject}</Text><Text style={s.meta}>{t(`support.category.${r.category}`)} · {new Date(r.created_at).toLocaleDateString(language)}</Text></View><Icon name="chevron-forward" size={17} color={C.textMuted}/></View><View style={[s.badge,{backgroundColor:`${c}18`}]}><Text style={{fontSize:10,fontWeight:'800',color:c}}>{t(`support.status.${r.status}`)}</Text></View></TouchableOpacity>}):<View style={s.empty}><View style={s.emptyIcon}><Icon name="chatbox-ellipses-outline" size={34} color={C.accent}/></View><Text style={s.emptyTitle}>{t('support.list.emptyTitle')}</Text><Text style={s.emptyText}>{t('support.list.emptyText')}</Text><TouchableOpacity style={s.emptyButton} onPress={()=>navigation.navigate('ReportProblem')}><Text style={s.emptyButtonText}>{t('support.list.create')}</Text></TouchableOpacity></View>}<Text style={s.footer}>Spendly © 2026</Text></ScrollView>}</View>}
function styles(C){return StyleSheet.create({flex:{flex:1,backgroundColor:C.bg},top:{paddingTop:56,paddingHorizontal:20,paddingBottom:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},round:{width:40,height:40,borderRadius:20,backgroundColor:C.surface,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center'},topTitle:{fontSize:17,fontWeight:'700',color:C.textPrimary},loading:{flex:1,alignItems:'center',justifyContent:'center'},loadingText:{marginTop:12,color:C.textSecondary},content:{paddingHorizontal:20,paddingBottom:40},filters:{gap:8,paddingBottom:18},chip:{paddingHorizontal:14,minHeight:38,borderRadius:999,borderWidth:1,borderColor:C.border,backgroundColor:C.surface,justifyContent:'center'},chipOn:{backgroundColor:C.accentDim,borderColor:`${C.accent}55`},chipText:{fontSize:11,fontWeight:'700',color:C.textSecondary},chipTextOn:{color:C.accent},card:{backgroundColor:C.surface,borderRadius:20,borderWidth:1,borderColor:C.border,padding:16,marginBottom:13,overflow:'hidden'},bar:{position:'absolute',left:0,top:0,bottom:0,width:4},header:{flexDirection:'row',alignItems:'center',gap:11},icon:{width:42,height:42,borderRadius:13,alignItems:'center',justifyContent:'center'},subject:{fontSize:15,fontWeight:'800',color:C.textPrimary},meta:{marginTop:4,fontSize:10,color:C.textSecondary},badge:{alignSelf:'flex-start',marginTop:13,paddingHorizontal:10,paddingVertical:5,borderRadius:999},empty:{backgroundColor:C.surface,borderRadius:24,borderWidth:1,borderColor:C.border,padding:28,alignItems:'center',marginTop:20},emptyIcon:{width:68,height:68,borderRadius:34,backgroundColor:C.accentDim,alignItems:'center',justifyContent:'center'},emptyTitle:{marginTop:16,fontSize:18,fontWeight:'800',color:C.textPrimary,textAlign:'center'},emptyText:{marginTop:8,fontSize:13,color:C.textSecondary,textAlign:'center',lineHeight:20},emptyButton:{height:46,borderRadius:14,backgroundColor:C.accent,justifyContent:'center',paddingHorizontal:20,marginTop:18},emptyButtonText:{fontSize:13,fontWeight:'800',color:C.buttonText||C.bg},footer:{marginTop:28,textAlign:'center',fontSize:12,color:C.textMuted,fontWeight:'600'}})}
