import React, { useMemo, useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, StatusBar, KeyboardAvoidingView, Platform, ScrollView, Alert, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../context/ThemeContext';
import { useLanguage } from '../context/LanguageContext';

import AsyncStorage from '@react-native-async-storage/async-storage';
import { resetPassword } from '../services/authService';
export default function ResetPasswordScreen({navigation,route}){
 const token=route?.params?.resetToken||''; const {colors:COLORS,isDark}=useTheme(); const {t}=useLanguage(); const styles=useMemo(()=>createStyles(COLORS),[COLORS]);
 const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [show,setShow]=useState(false);const [showConfirm,setShowConfirm]=useState(false);const [loading,setLoading]=useState(false);
 const submit=async()=>{if(!token)return Alert.alert(t('passwordRecovery.common.errorTitle'),t('passwordRecovery.errors.invalidRequest'));if(password.length<8)return Alert.alert(t('passwordRecovery.common.errorTitle'),t('passwordRecovery.errors.passwordLength'));if(password!==confirm)return Alert.alert(t('passwordRecovery.common.errorTitle'),t('passwordRecovery.errors.passwordMismatch'));try{setLoading(true);await resetPassword(token,password);await AsyncStorage.multiRemove(['access_token','pin_failed_attempts','pin_locked_until']);Alert.alert(t('passwordRecovery.reset.successTitle'),t('passwordRecovery.reset.successText'),[{text:t('passwordRecovery.reset.goToLogin'),onPress:()=>navigation.reset({index:0,routes:[{name:'Login'}]})}]);}catch(e){Alert.alert(t('passwordRecovery.common.errorTitle'),e.message||t('passwordRecovery.errors.reset'));}finally{setLoading(false)}};
 return <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':'height'}><StatusBar barStyle={isDark?'light-content':'dark-content'} backgroundColor={COLORS.bg}/><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="always" removeClippedSubviews={false}>
 <View style={styles.topBar}><TouchableOpacity style={styles.back} onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" size={22} color={COLORS.textPrimary}/></TouchableOpacity><Text style={styles.topTitle}>{t('passwordRecovery.reset.title')}</Text><View style={{width:42}}/></View>
 <View style={styles.card}><View style={styles.icon}><Ionicons name="lock-closed-outline" size={32} color={COLORS.accent}/></View><Text style={styles.title}>{t('passwordRecovery.reset.heading')}</Text><Text style={styles.subtitle}>{t('passwordRecovery.reset.subtitle')}</Text>
 <Text style={styles.label}>{t('passwordRecovery.reset.passwordLabel')}</Text><View style={styles.inputWrap}><Ionicons name="lock-closed-outline" size={18} color={COLORS.textMuted}/><TextInput style={styles.input} value={password} onChangeText={setPassword} secureTextEntry={!show} autoCapitalize="none" placeholder={t('passwordRecovery.reset.passwordPlaceholder')} placeholderTextColor={COLORS.textMuted}/><TouchableOpacity onPress={()=>setShow(v=>!v)}><Ionicons name={show?'eye-off-outline':'eye-outline'} size={20} color={COLORS.textMuted}/></TouchableOpacity></View>
 <Text style={[styles.label,{marginTop:18}]}>{t('passwordRecovery.reset.confirmLabel')}</Text><View style={styles.inputWrap}><Ionicons name="shield-checkmark-outline" size={18} color={COLORS.textMuted}/><TextInput style={styles.input} value={confirm} onChangeText={setConfirm} secureTextEntry={!showConfirm} autoCapitalize="none" placeholder={t('passwordRecovery.reset.confirmPlaceholder')} placeholderTextColor={COLORS.textMuted}/><TouchableOpacity onPress={()=>setShowConfirm(v=>!v)}><Ionicons name={showConfirm?'eye-off-outline':'eye-outline'} size={20} color={COLORS.textMuted}/></TouchableOpacity></View>
 <View style={styles.info}><Ionicons name="information-circle-outline" size={18} color={COLORS.accent}/><Text style={styles.infoText}>{t('passwordRecovery.reset.requirements')}</Text></View>
 <TouchableOpacity style={[styles.primary,loading&&styles.disabled]} onPress={submit} disabled={loading}>{loading?<ActivityIndicator color={COLORS.buttonText||COLORS.bg}/>:<Ionicons name="checkmark-circle-outline" size={20} color={COLORS.buttonText||COLORS.bg}/>}<Text style={styles.primaryText}>{loading?t('passwordRecovery.reset.saving'):t('passwordRecovery.reset.save')}</Text></TouchableOpacity></View><Text style={styles.footer}>Spendly © 2026</Text></ScrollView></KeyboardAvoidingView>
}
function createStyles(C){return StyleSheet.create({flex:{flex:1,backgroundColor:C.bg},content:{flexGrow:1,paddingTop:56,paddingHorizontal:20,paddingBottom:40},topBar:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:30},back:{width:42,height:42,borderRadius:21,backgroundColor:C.surface,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center'},topTitle:{fontSize:17,fontWeight:'800',color:C.textPrimary},card:{backgroundColor:C.surface,borderRadius:24,borderWidth:1,borderColor:C.border,padding:22},icon:{width:64,height:64,borderRadius:32,backgroundColor:C.accentDim,alignItems:'center',justifyContent:'center',marginBottom:18},title:{fontSize:24,fontWeight:'800',color:C.textPrimary},subtitle:{marginTop:8,fontSize:14,lineHeight:21,color:C.textSecondary,marginBottom:26},label:{fontSize:12,fontWeight:'700',color:C.textSecondary,textTransform:'uppercase',marginBottom:8},inputWrap:{minHeight:54,borderRadius:15,backgroundColor:C.surfaceHigh,borderWidth:1,borderColor:C.border,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:10},input:{flex:1,fontSize:15,color:C.textPrimary,paddingVertical:0},info:{marginTop:18,borderRadius:14,backgroundColor:C.surfaceHigh,padding:14,flexDirection:'row',gap:10},infoText:{flex:1,fontSize:12,lineHeight:18,color:C.textSecondary},primary:{minHeight:56,borderRadius:16,backgroundColor:C.accent,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,marginTop:20},disabled:{opacity:.65},primaryText:{fontSize:15,fontWeight:'800',color:C.buttonText||C.bg},footer:{marginTop:28,fontSize:12,fontWeight:'600',color:C.textMuted,textAlign:'center'}})}
