import React, { useMemo, useState } from 'react';
import { View, Text, TextInput, TouchableOpacity, StyleSheet, StatusBar, KeyboardAvoidingView, Platform, ScrollView, Alert, ActivityIndicator } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../context/ThemeContext';
import { useLanguage } from '../context/LanguageContext';

import { forgotPassword, verifyResetCode } from '../services/authService';
const CODE_LENGTH=6, RESEND_SECONDS=60;
export default function VerifyResetCodeScreen({navigation,route}){
 const email=route?.params?.email||''; const {colors:COLORS,isDark}=useTheme(); const {t}=useLanguage(); const styles=useMemo(()=>createStyles(COLORS),[COLORS]);
 const [code,setCode]=useState(''); const [loading,setLoading]=useState(false); const [resending,setResending]=useState(false); const [seconds,setSeconds]=useState(RESEND_SECONDS);
 React.useEffect(()=>{if(seconds<=0)return;const i=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(i)},[seconds]);
 const verify=async()=>{const c=code.replace(/\D/g,'').slice(0,6);if(c.length!==6)return Alert.alert(t('passwordRecovery.common.errorTitle'),t('passwordRecovery.errors.codeIncomplete'));try{setLoading(true);const data=await verifyResetCode(email,c);navigation.replace('ResetPassword',{resetToken:data.reset_token});}catch(e){Alert.alert(t('passwordRecovery.common.errorTitle'),e.message||t('passwordRecovery.errors.verifyCode'));}finally{setLoading(false)}};
 const resend=async()=>{if(seconds>0||resending)return;try{setResending(true);await forgotPassword(email);setCode('');setSeconds(RESEND_SECONDS);Alert.alert(t('passwordRecovery.verify.resentTitle'),t('passwordRecovery.verify.resentText'));}catch(e){Alert.alert(t('passwordRecovery.common.errorTitle'),e.message||t('passwordRecovery.errors.resend'));}finally{setResending(false)}};
 const masked=email?email.replace(/^(.{2}).*(@.*)$/,'$1••••$2'):'';
 return <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS==='ios'?'padding':'height'}><StatusBar barStyle={isDark?'light-content':'dark-content'} backgroundColor={COLORS.bg}/><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="always" removeClippedSubviews={false}>
 <View style={styles.topBar}><TouchableOpacity style={styles.back} onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" size={22} color={COLORS.textPrimary}/></TouchableOpacity><Text style={styles.topTitle}>{t('passwordRecovery.verify.title')}</Text><View style={{width:42}}/></View>
 <View style={styles.card}><View style={styles.icon}><Ionicons name="keypad-outline" size={32} color={COLORS.accent}/></View><Text style={styles.title}>{t('passwordRecovery.verify.heading')}</Text><Text style={styles.subtitle}>{t('passwordRecovery.verify.subtitle')}</Text><Text style={styles.email}>{masked}</Text>
 <View style={styles.codeRow}>{Array.from({length:6}).map((_,i)=><View key={i} style={[styles.codeBox,code[i]&&styles.codeFilled]}><Text style={styles.codeDigit}>{code[i]||''}</Text></View>)}</View>
 <TextInput style={styles.codeInput} value={code} onChangeText={v=>setCode(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" textContentType="oneTimeCode" maxLength={6} autoFocus/>
 <TouchableOpacity style={[styles.primary,loading&&styles.disabled]} onPress={verify} disabled={loading}>{loading?<ActivityIndicator color={COLORS.buttonText||COLORS.bg}/>:<Ionicons name="checkmark-circle-outline" size={20} color={COLORS.buttonText||COLORS.bg}/>}<Text style={styles.primaryText}>{loading?t('passwordRecovery.verify.verifying'):t('passwordRecovery.verify.confirm')}</Text></TouchableOpacity>
 <View style={styles.resendRow}><Text style={styles.resendQ}>{t('passwordRecovery.verify.noCode')}</Text><TouchableOpacity onPress={resend} disabled={seconds>0||resending}><Text style={[styles.resend,(seconds>0||resending)&&styles.resendDisabled]}>{resending?t('passwordRecovery.verify.resending'):seconds>0?t('passwordRecovery.verify.resendIn').replace('{seconds}',String(seconds)):t('passwordRecovery.verify.resend')}</Text></TouchableOpacity></View>
 <View style={styles.info}><Ionicons name="time-outline" size={18} color={COLORS.accent}/><Text style={styles.infoText}>{t('passwordRecovery.verify.expiration')}</Text></View></View><Text style={styles.footer}>Spendly © 2026</Text></ScrollView></KeyboardAvoidingView>
}
function createStyles(C){return StyleSheet.create({flex:{flex:1,backgroundColor:C.bg},content:{flexGrow:1,paddingTop:56,paddingHorizontal:20,paddingBottom:40},topBar:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:30},back:{width:42,height:42,borderRadius:21,backgroundColor:C.surface,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center'},topTitle:{fontSize:17,fontWeight:'800',color:C.textPrimary},card:{backgroundColor:C.surface,borderRadius:24,borderWidth:1,borderColor:C.border,padding:22},icon:{width:64,height:64,borderRadius:32,backgroundColor:C.accentDim,alignItems:'center',justifyContent:'center',marginBottom:18},title:{fontSize:24,fontWeight:'800',color:C.textPrimary},subtitle:{marginTop:8,fontSize:14,lineHeight:21,color:C.textSecondary},email:{marginTop:9,fontSize:13,fontWeight:'700',color:C.accent},codeRow:{marginTop:28,flexDirection:'row',justifyContent:'space-between',gap:8},codeBox:{flex:1,aspectRatio:.82,maxHeight:62,borderRadius:14,backgroundColor:C.surfaceHigh,borderWidth:1,borderColor:C.border,alignItems:'center',justifyContent:'center'},codeFilled:{backgroundColor:C.accentDim,borderColor:C.accent},codeDigit:{fontSize:24,fontWeight:'800',color:C.textPrimary},codeInput:{marginTop:14,minHeight:48,borderRadius:14,backgroundColor:C.surfaceHigh,borderWidth:1,borderColor:C.border,color:C.textPrimary,textAlign:'center',fontSize:20,letterSpacing:12},primary:{minHeight:56,borderRadius:16,backgroundColor:C.accent,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:9,marginTop:24},disabled:{opacity:.65},primaryText:{fontSize:15,fontWeight:'800',color:C.buttonText||C.bg},resendRow:{marginTop:20,flexDirection:'row',justifyContent:'center',flexWrap:'wrap',gap:6},resendQ:{fontSize:13,color:C.textSecondary},resend:{fontSize:13,fontWeight:'800',color:C.accent},resendDisabled:{color:C.textMuted},info:{marginTop:20,borderRadius:14,backgroundColor:C.surfaceHigh,padding:14,flexDirection:'row',gap:10},infoText:{flex:1,fontSize:12,lineHeight:18,color:C.textSecondary},footer:{marginTop:28,fontSize:12,fontWeight:'600',color:C.textMuted,textAlign:'center'}})}
